### ISSUE TITLE
php_network_getaddresses: getaddrinfo failed: Name or service not known

### ISSUE THREAD

**Issue by zhanghuanchong** [walkor/GlobalData#4]
```
Exception: php_network_getaddresses: getaddrinfo failed: Name or service not known in /var/www/xxx/vendor/workerman/globaldata/src/Client.php:69
Stack trace:
#0 /var/www/xxx/vendor/workerman/globaldata/src/Client.php(138): GlobalData\Client->getConnection('SEND_EMAIL_1')
#1 /var/www/xxx/EmailHandler.php(68): GlobalData\Client->__get('SEND_EMAIL_1')
```

Please help!

**Comment by walkor** [comment]
这个域名在你的服务器没办法解析，请确认域名是否准确。SEND_EMAIL_1
